name    'hastexo/kickstack'
version '0.2.0'
source  'https://github.com/hastexo/kickstack'
author  'Florian Haas,Syed Armani,Andreas Kurz,Martin Loschwitz'
license 'Apache License 2.0'
summary 'Rapid OpenStack deployment with puppet-dashboard or any other Puppet ENC'
description 'Puppet module to rapidly install and deploy OpenStack, based on the Stackforge Puppet modules, configurable through parameters from puppet-dashboard, Puppet Enterprise, The Foreman, or any other Puppet External Node Classifier (ENC)'
project_page 'https://github.com/hastexo/kickstack'

dependency 'hastexo/exportfact', '>= 0.1.1'
dependency 'puppetlabs/lvm', '>= 0.1.2'
dependency 'puppetlabs/openstack', '>= 3.0.0'
dependency 'rgevaert/pwgen', '>= 0.0.1'
